### ISSUE TITLE
Error on installation in Chrome 128.0.6613.138: popup.html missing

### ISSUE THREAD

**Issue by Nellman1508** [nikonowiczp/simplifier-tab-plugin#1]
Unfortunately, when installing the Plugin, there is an error.
<img width="421" alt="image" src="https://github.com/user-attachments/assets/e2837ad8-4eaf-475a-92a5-963f3c0c7a6b">
I suspect the popup.html is missing.

**Comment by nikonowiczp** [comment]
I have removed popup from manifest.json. Can you confirm whether it is working correctly now?

**Comment by Nellman1508** [comment]
Looks Good, the is now correctly renamed.
Thanks for the quick response.
